name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, Contributor Congratulations:tada: on opening your first issue will look into it asap. '' first issue'
        pr-message: 'Hey, Contributor Congratulations:tada: on making your first pull request hope to see more contribution from you'' first pr'
